name: CI
on:
    push:
    pull_request:
    workflow_dispatch:
    #schedule:
    #    - cron: '42 5 * * 0'
jobs:
  perl-job:
    runs-on: ubuntu-latest
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
        
      - name: Start Redis Services
        run: docker-compose up -d

      - name: Setup Perl
        uses: shogo8001/actions-setup-perl@v1
        with:
          perl-version: '5.42'
      
      - name: Prepare for release tests
        run: |
            cpanm --installdep .
            cpanm --notest Test::CheckManifest Test::Pod::Coverage Pod::Coverage Test::Pod
            
      - name: Release tests
        env:
          RELEASE_TESTING: 1
          REDIS_HOST: redis
          REDIS_AUTH: redis-auth
        run: |
            perl Makefile.PL
            make
            make test
